# Configuration file for Nginx

upstream divisor_pdf_app {
    server unix:/home/rodrigostolben/Projetos/divisor_pdf/divisor_pdf.sock fail_timeout=0;
}

server {
    listen 80;
    server_name localhost; # Substitua pelo domínio em produção

    client_max_body_size 512M;

    keepalive_timeout 5;

    # Logs
    access_log /var/log/nginx/divisor_pdf.access.log;
    error_log /var/log/nginx/divisor_pdf.error.log info;

    # Django Static Files
    location /static/ {
        alias /home/rodrigostolben/Projetos/divisor_pdf/staticfiles/;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    # Django Media Files (Downloads ZIP temporários)
    location /media/ {
        alias /home/rodrigostolben/Projetos/divisor_pdf/media/;
        expires off;
        add_header Cache-Control "private, no-store, no-cache, must-revalidate, proxy-revalidate";
    }

    # Dynamic requests proxy to Gunicorn
    location / {
        try_files $uri @proxy_to_app;
    }

    location @proxy_to_app {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        # Evita redirecionamentos indesejados no Gunicorn
        proxy_redirect off;
        proxy_pass http://divisor_pdf_app;
        
        # Aumentar timeouts para uploads e processamentos longos
        proxy_read_timeout 300s;
        proxy_connect_timeout 300s;
        proxy_send_timeout 300s;
    }

    # Página de erro customizada
    error_page 500 502 503 504 /500.html;
    location = /500.html {
        root /home/rodrigostolben/Projetos/divisor_pdf/templates/;
    }
}
