# Generated by Django 6.0.5 on 2026-05-31 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SplitJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, help_text='Chave da sessão do usuário', max_length=40)),
                ('task_id', models.CharField(blank=True, help_text='ID da task Celery', max_length=255, null=True, unique=True)),
                ('original_filenames', models.JSONField(default=list, help_text='Lista de nomes dos PDFs enviados')),
                ('total_input_size_mb', models.FloatField(default=0, help_text='Tamanho total dos uploads em MB')),
                ('max_size_mb', models.FloatField(help_text='Tamanho máximo solicitado pelo usuário em MB')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Concluído'), ('failed', 'Falhou')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0, help_text='Progresso do processamento (0-100)')),
                ('total_output_files', models.IntegerField(blank=True, help_text='Quantidade de PDFs gerados', null=True)),
                ('output_zip_path', models.CharField(blank=True, help_text='Caminho do arquivo ZIP resultante', max_length=500)),
                ('error_message', models.TextField(blank=True, help_text='Mensagem de erro caso tenha falhado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cleaned_up', models.BooleanField(default=False, help_text='Se os arquivos já foram removidos do disco')),
            ],
            options={
                'verbose_name': 'Trabalho de Divisão',
                'verbose_name_plural': 'Trabalhos de Divisão',
                'ordering': ['-created_at'],
            },
        ),
    ]
