# Generated by Django 6.0.5 on 2026-05-31 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='splitjob',
            name='compress_level',
            field=models.CharField(choices=[('none', 'Sem Compressão'), ('low', 'Qualidade Alta (Baixa Compressão)'), ('medium', 'Qualidade Média (Compressão Moderada)'), ('high', 'Qualidade Baixa (Alta Compressão)')], default='none', help_text='Nível de compressão desejado via Ghostscript', max_length=20),
        ),
        migrations.AddField(
            model_name='splitjob',
            name='should_split',
            field=models.BooleanField(default=True, help_text='Se deve dividir os PDFs em partes menores após compressão'),
        ),
        migrations.AddField(
            model_name='splitjob',
            name='total_output_size_mb',
            field=models.FloatField(blank=True, help_text='Tamanho do arquivo ZIP resultante em MB', null=True),
        ),
        migrations.AlterField(
            model_name='splitjob',
            name='max_size_mb',
            field=models.FloatField(blank=True, help_text='Tamanho máximo solicitado pelo usuário em MB (opcional se não dividir)', null=True),
        ),
    ]
