# Generated by Django 6.0.8 on 2026-09-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OCRJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, help_text='Chave da sessão do usuário', max_length=40)),
                ('task_id', models.CharField(blank=True, help_text='ID da task Celery', max_length=255, null=True, unique=True)),
                ('original_filenames', models.JSONField(default=list, help_text='Lista de nomes dos PDFs enviados')),
                ('total_input_size_mb', models.FloatField(default=0, help_text='Tamanho total dos uploads em MB')),
                ('idioma', models.CharField(choices=[('por', 'Português'), ('eng', 'Inglês'), ('por+eng', 'Português + Inglês')], default='por', help_text='Idioma(s) usados pelo Tesseract no reconhecimento', max_length=20)),
                ('forcar_ocr', models.BooleanField(default=False, help_text='Refaz o OCR mesmo em páginas que já têm texto. Sem isso, páginas com texto nativo são preservadas como estão.')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Concluído'), ('failed', 'Falhou')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0, help_text='Progresso do processamento (0-100)')),
                ('total_output_files', models.IntegerField(blank=True, help_text='Quantidade de PDFs reconhecidos', null=True)),
                ('output_pdf_path', models.CharField(blank=True, help_text='Caminho do PDF pesquisável (ou do ZIP com eles)', max_length=500)),
                ('output_md_path', models.CharField(blank=True, help_text='Caminho do Markdown (ou do ZIP com eles)', max_length=500)),
                ('output_pdf_size_mb', models.FloatField(blank=True, help_text='Tamanho do PDF em MB', null=True)),
                ('output_md_size_mb', models.FloatField(blank=True, help_text='Tamanho do .md em MB', null=True)),
                ('total_caracteres', models.IntegerField(blank=True, help_text='Caracteres reconhecidos, somando todos os arquivos', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Mensagem de erro caso tenha falhado')),
                ('processing_warnings', models.JSONField(blank=True, default=list, help_text='Avisos sobre limitações encontradas no processamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cleaned_up', models.BooleanField(default=False, help_text='Se os arquivos já foram removidos do disco')),
            ],
            options={
                'verbose_name': 'Trabalho de OCR',
                'verbose_name_plural': 'Trabalhos de OCR',
                'ordering': ['-created_at'],
            },
        ),
    ]
